version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: adham
      POSTGRES_PASSWORD: adham
      POSTGRES_PORT: 5432
      POSTGRES_DB: coffedatabase  # This will auto-create the database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: {}