# Generated by Django 5.1.5 on 2025-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cups_sold', models.IntegerField(verbose_name='Cups Sold')),
                ('cup_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Cup')),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Sale')),
                ('customer_count', models.IntegerField(verbose_name='Customer Count')),
                ('discount', models.IntegerField(verbose_name='Discount Applied (in USD)')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Profit / Loss')),
            ],
        ),
    ]
